function [figNum] = fcn_plotGenerateFigureNumber(fieldString,sensorString,structureString)
%fcn_generateFigureNumber generates a figure number based on the details
%used.

% This is the ordering of how fields within structures are likely to appear
% - we use this to create figure nubmers automatically in the plotting that
% follows.

% Revision history:
% 2019_11_25 - first write of this function by sbrennan@psu.edu
% 2019_11_27 - made error catching more verbose


flag_do_debug = 1;

%% Let the user know what we are doing
if flag_do_debug
    % Grab function name
    st = dbstack;
    namestr = st.name;
    
    % Show what we are doing
    fprintf(1,'\t\tWithin subfunction: %s\n',namestr);
    fprintf(1,'\t\tCalculating a figure number for: \n');
    fprintf(1,'\t\t\tStructure: %s \n',structureString);
    fprintf(1,'\t\t\tSensor: %s \n',sensorString);
    fprintf(1,'\t\t\tField: %s \n',fieldString);
end

%%
% THE TEMPLATE FOR ALL PLOTTING
fieldOrdering = [...    
    {'Yaw_deg'},...                 % Yaw variables
    {'Yaw_deg_from_position'},... 
    {'Yaw_deg_from_velocity'},... 
    {'All_SingleSensor_Yaw_deg'},... 
    {'All_AllSensors_Yaw_deg'},...
    {'Yaw_deg_merged'},...
    {'All_AllSensors_Yaw_deg_merged'},...    
    {'ZGyro'},...                   % Yawrate (ZGyro) variables
    {'All_AllSensors_ZGyro'},... 
    {'ZGyro_merged'},...
    {'All_AllSensors_ZGyro_merged'},...    
    {'velMagnitude'},...            % velMagnitude variables
    {'All_AllSensors_velMagnitude'},...        
    {'XAccel'},...                  % XAccel variables
    {'All_AllSensors_XAccel'},...
    {'xEast_increments'},...        % Position increment variables
    {'All_AllSensors_xEast_increments'},...
    {'yNorth_increments'},...
    {'All_AllSensors_yNorth_increments'},...
    {'zUp_increments'},...
    {'All_AllSensors_zUp_increments'},...
    {'XYplot'},...                  % XY plots
    {'All_AllSensors_XYplot'},...
    {'xEast'},...                   % xEast and yNorth plots
    {'All_AllSensors_xEast'},...
    {'yNorth'},...
    {'All_AllSensors_yNorth'},...
    {'zUp'},...
    {'All_AllSensors_zUp'},...
    {'DGPS_is_active'},...
    {'All_AllSensors_DGPS_is_active'},...
    %     {'velNorth'},...                % Remaining are not yet plotted - just kept here for now as  placeholders
    %     {'velEast'},...
    %     {'velUp'},...
    %     {'Roll_deg'},...
    %     {'Pitch_deg'},...
    %     {'xy_increments'}... % Confirmed
    %     {'YAccel'},...
    %     {'ZAccel'},...
    %     {'XGyro'},...
    %     {'YGyro'},...
    %     {'VelocityR},...

    ];

% This is the ordering of how sensors are likely to appear - we use this
% to create figure nubmers
sensorOrdering = [...
    {'GPS_Hemisphere'},...
    {'GPS_Novatel'},...
    {'GPS_Garmin'},...
    {'IMU_Novatel'},...
    {'IMU_ADIS'},...
    {'Input_Steering'},...
    {'Encoder_RearWheels'},...
    {'VelocityProjectedByYaw'},...
    {'MergedGPS'},...
    {'MergedIMU'},...    
];   

% This is the ordering of how structures are likely to appear - we use this
% to create figure nubmers
structureOrdering = [...
    {'rawData'},...
    {'rawDataTimeFixed'},...
    {'rawDataWithSigmas'},...
    {'rawDataWithSigmasAndMedianFiltered'},...
    {'cleanData'},...
    {'cleanAndTimeAlignedData'},...
    {'timeFilteredData'},...
    {'mergedData'},...
    {'mergedDataNoJumps'},...
    {'mergedByKFData'},...
];    


structure_number = find(strcmp(structureOrdering,structureString)==1);
if isempty(structure_number)
    error('The data structure: %s is unknown. Was this defined in the master template in this function?',structureString);
end

if strncmpi(fieldString,'All_All',7) % Skip the sensor number if many sensors are involved
    sensor_number = length(sensorOrdering)+1;
else
    sensor_number = find(strcmp(sensorOrdering,sensorString)==1);
    if isempty(sensor_number)
        error('The sensor: %s is unknown. Was this defined in the master template in this function?',sensorString);
    end
end

field_number = find(strcmp(fieldOrdering,fieldString)==1);
if isempty(field_number)
    error('The sensor field: %s is unknown. Was this defined in the master template in this function?',sensorString);
end


figNum = structure_number*1000 + sensor_number*100 + field_number;

if flag_do_debug
    fprintf(1,'\t\t\tThe fig number was calculated to be: %d\n',figNum);
    fprintf(1,'\t\tExiting subfunction: %s\n',namestr);
end

return

